<?php

// database/seeders/TemplateSeeder.php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Template;
use App\Models\TemplateCategory;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $pernikahan = TemplateCategory::where('slug', 'pernikahan')->firstOrFail();
        $storybook  = TemplateCategory::where('slug', 'storybook')->firstOrFail();
        $cinema     = TemplateCategory::where('slug', 'cinema')->firstOrFail();

        $weddingDemo = [
            'details' => [
                'groom_name'         => 'Ahmad Rizky',
                'bride_name'         => 'Siti Nurhaliza',
                'groom_photo_url'    => '/image/demo-image/groom.png',
                'bride_photo_url'    => '/image/demo-image/bride.png',
                'groom_parent_names' => 'Bpk. Hasan & Ibu Fatimah',
                'bride_parent_names' => 'Bpk. Rahmat & Ibu Aminah',
                'groom_instagram'    => 'ahmadrizky',
                'bride_instagram'    => 'sitinurhaliza',
                'opening_text'       => "Bismillahirrahmanirrahim\nDengan memohon rahmat dan ridho Allah SWT, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri pernikahan kami.",
                'closing_text'       => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.',
            ],
            'events' => [
                [
                    'event_name'    => 'Akad Nikah',
                    'event_date'    => '2026-06-15',
                    'start_time'    => '08:00',
                    'end_time'      => '10:00',
                    'venue_name'    => 'Masjid Al-Ikhlas',
                    'venue_address' => 'Jl. Sudirman No. 123, Jakarta Selatan',
                    'maps_url'      => 'https://maps.google.com/?q=-6.2088,106.8456',
                ],
                [
                    'event_name'    => 'Resepsi',
                    'event_date'    => '2026-06-15',
                    'start_time'    => '11:00',
                    'end_time'      => '14:00',
                    'venue_name'    => 'Ballroom Hotel Mulia',
                    'venue_address' => 'Jl. Asia Afrika No. 8, Jakarta Selatan',
                    'maps_url'      => 'https://maps.google.com/?q=-6.2150,106.8070',
                ],
            ],
            'gallery' => [
                '/image/demo-image/galeri/galeri-0.webp',
                '/image/demo-image/galeri/galeri-1.webp',
                '/image/demo-image/galeri/galeri-0.webp',
                '/image/demo-image/galeri/galeri-1.webp',
            ],
            'gift' => [
                'accounts' => [
                    ['bank' => 'BCA',      'account_number' => '1234567890', 'account_name' => 'Ahmad Rizky'],
                    ['bank' => 'Mandiri',  'account_number' => '0987654321', 'account_name' => 'Siti Nurhaliza'],
                ],
            ],
            'love_story' => [
                [
                    'date'        => 'Maret 2020',
                    'title'       => 'Pertama Bertemu',
                    'description' => 'Kami pertama kali bertemu di sebuah seminar kampus. Satu tatapan yang tak terlupakan menjadi awal dari segalanya.',
                ],
                [
                    'date'        => 'Juni 2020',
                    'title'       => 'Jatuh Hati',
                    'description' => 'Setelah beberapa bulan sering menghabiskan waktu bersama, kami sadar ada sesuatu yang istimewa di antara kami.',
                ],
                [
                    'date'        => 'Desember 2021',
                    'title'       => 'Resmi Bersama',
                    'description' => 'Di bawah langit berbintang, Ahmad memberanikan diri mengungkapkan perasaannya. Siti pun menerima dengan senyum termanis.',
                ],
                [
                    'date'        => 'Juni 2026',
                    'title'       => 'Menuju Pelaminan',
                    'description' => 'Dengan restu kedua keluarga dan doa dari orang-orang tercinta, kami siap melangkah ke babak baru kehidupan bersama.',
                ],
            ],
        ];

        $templates = [
            // ── Pernikahan ─────────────────────────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Bunga Abadi',
                'slug'           => 'bunga-abadi',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan elegan dengan sentuhan bunga dan nuansa hangat keemasan.',
                'default_config' => [
                    'primary_color'   => '#D4A373',
                    'secondary_color' => '#FEFAE0',
                    'accent_color'    => '#CCD5AE',
                    'font_title'      => 'Playfair Display',
                    'font_body'       => 'Poppins',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'fade-up',
                    'bg_pattern'      => 'floral',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#D4A373',
                    'secondary_color' => '#FEFAE0',
                    'font_title'      => 'Playfair Display',
                    'font_body'       => 'Poppins',
                ]]),
                'tier'           => 'free',
                'is_active'      => true,
                'sort_order'     => 1,
            ],
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Langit Senja',
                'slug'           => 'langit-senja',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan romantis dengan palet warna sunset yang memukau.',
                'default_config' => [
                    'primary_color'   => '#E57070',
                    'secondary_color' => '#FDE8E8',
                    'accent_color'    => '#F4A261',
                    'font_title'      => 'Cormorant Garamond',
                    'font_body'       => 'Lato',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'slide-up',
                    'bg_pattern'      => 'watercolor',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#E57070',
                    'secondary_color' => '#FDE8E8',
                    'font_title'      => 'Cormorant Garamond',
                    'font_body'       => 'Lato',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 2,
            ],
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Hijau Daun',
                'slug'           => 'hijau-daun',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan segar dengan nuansa alam dan dedaunan hijau.',
                'default_config' => [
                    'primary_color'   => '#52796F',
                    'secondary_color' => '#CAD2C5',
                    'accent_color'    => '#84A98C',
                    'font_title'      => 'DM Serif Display',
                    'font_body'       => 'Nunito',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'fade-in',
                    'bg_pattern'      => 'leaves',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#52796F',
                    'secondary_color' => '#CAD2C5',
                    'font_title'      => 'DM Serif Display',
                    'font_body'       => 'Nunito',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 3,
            ],

            // ── Storybook (scene/illustrated templates) ────────────
            [
                'category_id'    => $storybook->id,
                'name'           => 'Beach',
                'slug'           => 'beach',
                'thumbnail_url'  => '/images/templates/beach/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya pantai tropis — jelajahi setiap bagian undangan layaknya petualangan seru di tepi laut.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 5,
            ],
            [
                'category_id'    => $storybook->id,
                'name'           => 'Garden',
                'slug'           => 'garden',
                'thumbnail_url'  => '/images/templates/garden/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya taman bunga yang hidup — temukan setiap detail undangan di antara hamparan bunga dan pepohonan yang rimbun.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 6,
            ],
            [
                'category_id'    => $storybook->id,
                'name'           => 'Night Sky',
                'slug'           => 'night-sky',
                'thumbnail_url'  => '/images/templates/night-sky/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya langit malam berbintang — rayakan cinta di bawah ribuan bintang yang berkelip memukau.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 7,
            ],

            // ── Nusantara (Premium, dedicated renderer) ───────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Nusantara',
                'slug'           => 'nusantara',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan premium bergaya keraton Jawa — megah, sakral, dan agung. Dilengkapi animasi gapura, ornamen batik kawung, sulur lung-lungan, dan mandala teratai.',
                'default_config' => [
                    'primary_color'       => '#8B6914',
                    'primary_color_light' => '#C9A84C',
                    'secondary_color'     => '#F5F0E8',
                    'accent_color'        => '#6B1D1D',
                    'dark_bg'             => '#2C1810',
                    'font_title'          => 'Cinzel Decorative',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Crimson Text',
                    'layout'              => 'vertical-scroll',
                    'animation'           => 'javanese-gate',
                    'has_opening_animation' => true,
                    'has_parallax'          => true,
                    'has_countdown'         => true,
                    'ornament_style'        => 'javanese',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'       => '#8B6914',
                    'primary_color_light' => '#C9A84C',
                    'secondary_color'     => '#F5F0E8',
                    'accent_color'        => '#6B1D1D',
                    'dark_bg'             => '#2C1810',
                    'font_title'          => 'Cinzel Decorative',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Crimson Text',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 4,
            ],

            // ── Onyx Noir (Premium Luxury) ───────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Onyx Noir',
                'slug'           => 'onyx-noir',
                'thumbnail_url'  => '/images/templates/onyx-noir/thumbnail.webp',
                'description'    => 'Template pernikahan premium dark luxury — marmer hitam carrara, aksen gold leaf, dan wax seal yang pecah di tap pertama. Untuk pasangan yang menginginkan kesan museum-quality, formal-sophisticated, tanpa flora-fauna.',
                'default_config' => [
                    'primary_color'        => '#d4af37',
                    'primary_color_light'  => '#f3e5a0',
                    'secondary_color'      => '#b8941f',
                    'accent_color'         => '#d4af37',
                    'dark_bg'              => '#0a0a0a',
                    'bg_color'             => '#0a0a0a',
                    'text_color'           => '#f5f5f0',
                    'text_secondary'       => '#a8a8a8',
                    'font_title'           => 'Cormorant Garamond',
                    'font_heading'         => 'Tenor Sans',
                    'font_body'            => 'Inter',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'marble', 'value' => 'subtle'],
                        'couple'  => ['type' => 'marble', 'value' => 'subtle'],
                        'events'  => ['type' => 'color',  'value' => '#0a0a0a'],
                        'closing' => ['type' => 'marble', 'value' => 'strong'],
                    ],
                    'onyx_monogram_text'    => 'A & B',
                    'onyx_seal_motif'       => 'geometric',
                    'onyx_marble_intensity' => 'subtle',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'onyx_monogram_text'    => 'A & S',
                    'onyx_seal_motif'       => 'geometric',
                    'onyx_marble_intensity' => 'subtle',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 9,
            ],

            // ── Cinema ────────────────────────────────────────────
            [
                'category_id'    => $cinema->id,
                'name'           => 'Netflix',
                'slug'           => 'netflix',
                'thumbnail_url'  => null,
                'description'    => 'Template undangan pernikahan bertema Netflix — cinematic, bold, dan ikonik. Tamu diajak masuk lewat layar "Who\'s Watching?" sebelum menikmati undangan seperti sebuah Netflix Original.',
                'default_config' => [
                    'netflix_subtitle' => 'Sebuah Kisah Cinta',
                    'netflix_tags'     => ['#lovestory', '#romantic', '#halal', '#forever'],
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'netflix_subtitle' => 'Sebuah Kisah Cinta',
                    'netflix_tags'     => ['#lovestory', '#romantic', '#halal', '#forever'],
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 8,
            ],

            // ── Art Deco Gatsby (Premium, multi-phase orchestrator) ─
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Art Deco Gatsby',
                'slug'           => 'art-deco-gatsby',
                'thumbnail_url'  => '/images/templates/art-deco-gatsby/thumbnail.webp',
                'description'    => 'Opulent 1920s Gatsby — gold sunburst on near-black, chevron borders, fan motifs. Timeless luxury.',
                'default_config' => [
                    'primary_color'       => '#c9a961',
                    'primary_color_light' => '#f4ead5',
                    'secondary_color'     => '#1a3a2e',
                    'accent_color'        => '#c9a961',
                    'dark_bg'             => '#0d0d0d',
                    'font_title'          => 'Poiret One',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Lato',
                    'gallery_layout'      => 'grid',
                    'opening_style'       => 'fade',
                    'section_backgrounds' => [
                        'events'    => ['type' => 'color', 'value' => '#0d0d0d'],
                        'countdown' => ['type' => 'color', 'value' => '#1a1a1a'],
                    ],
                    'deco_monogram'        => 'auto',
                    'deco_sunburst_rays'   => 24,
                    'deco_accent_color'    => 'gold',
                    'deco_chevron_density' => 'medium',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'  => '#c9a961',
                    'dark_bg'        => '#0d0d0d',
                    'font_title'     => 'Poiret One',
                    'font_heading'   => 'Cormorant Garamond',
                    'font_body'      => 'Lato',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 9,
            ],

            // ── Velvet Burgundy (Premium, dedicated renderer) ─────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Velvet Burgundy',
                'slug'           => 'velvet-burgundy',
                'thumbnail_url'  => '/images/templates/velvet-burgundy/thumbnail.webp',
                'description'    => 'Undangan premium Victorian-modern: beludru maroon + filigree emas + segel lilin. Cocok untuk warna hangat klasik (akad/resepsi adat-modern).',
                'default_config' => [
                    'primary_color'           => '#5c1a1b',
                    'primary_color_light'     => '#8b1a1f',
                    'secondary_color'         => '#d4a574',
                    'accent_color'            => '#a87a4a',
                    'dark_bg'                 => '#3a0c0e',
                    'font_title'              => 'Playfair Display',
                    'font_heading'            => 'Cormorant SC',
                    'font_body'               => 'Crimson Text',
                    'gallery_layout'          => 'masonry',
                    'opening_style'           => 'fade',
                    'velvet_seal_monogram'    => 'A & S',
                    'velvet_seal_motif'       => 'rose',
                    'velvet_filigree_density' => 'medium',
                    'velvet_paper_panels'     => true,
                    'velvet_cover_subtitle'   => 'Sebuah Undangan Pernikahan',
                    'section_backgrounds'     => [
                        'events' => ['type' => 'color', 'value' => '#3a0c0e'],
                        'rsvp'   => ['type' => 'image', 'value' => '/images/templates/velvet-burgundy/paper-cream.webp'],
                        'gift'   => ['type' => 'image', 'value' => '/images/templates/velvet-burgundy/paper-cream.webp'],
                    ],
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'         => '#5c1a1b',
                    'secondary_color'       => '#d4a574',
                    'accent_color'          => '#a87a4a',
                    'dark_bg'               => '#3a0c0e',
                    'font_title'            => 'Playfair Display',
                    'font_heading'          => 'Cormorant SC',
                    'font_body'             => 'Crimson Text',
                    'velvet_seal_monogram'  => 'A & S',
                    'velvet_cover_subtitle' => 'Sebuah Undangan Pernikahan',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 14,
            ],

            // ── Belle Époque Parisian (Premium, watercolor multi-phase) ──
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Belle Époque Parisian',
                'slug'           => 'belle-epoque',
                'thumbnail_url'  => '/images/templates/belle-epoque/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema café Paris era Belle Époque — watercolor Eiffel, peony hand-painted, tipografi script tulisan tangan, dan postcard motif.',
                'default_config' => [
                    'primary_color'       => '#d4a5a5',
                    'primary_color_light' => '#fdf6ed',
                    'secondary_color'     => '#b8860b',
                    'accent_color'        => '#7a9b8e',
                    'dark_bg'             => '#3d3d3d',
                    'font_title'          => 'Italianno',
                    'font_heading'        => 'Cormorant SC',
                    'font_body'           => 'EB Garamond',
                    'gallery_layout'      => 'masonry',
                    'opening_style'       => 'fade',
                    'section_backgrounds' => [
                        'events'     => ['type' => 'color', 'value' => '#fdf6ed'],
                        'love_story' => ['type' => 'color', 'value' => '#fdf6ed'],
                        'gift'       => ['type' => 'color', 'value' => '#f7e9dc'],
                    ],
                    'bp_couple_initials'  => 'A & B',
                    'bp_postcard_city'    => 'JAKARTA',
                    'bp_destination_city' => 'PARIS',
                    'bp_floral_palette'   => 'mixed',
                    'bp_eiffel_visible'   => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'       => '#d4a5a5',
                    'primary_color_light' => '#fdf6ed',
                    'secondary_color'     => '#b8860b',
                    'accent_color'        => '#7a9b8e',
                    'font_title'          => 'Italianno',
                    'font_heading'        => 'Cormorant SC',
                    'font_body'           => 'EB Garamond',
                    'bp_postcard_city'    => 'JAKARTA',
                    'bp_destination_city' => 'PARIS',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 11,
            ],

            // ── Astronomy Celestial (Premium) ────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Astronomy Celestial',
                'slug'           => 'astronomy-celestial',
                'thumbnail_url'  => '/images/templates/astronomy-celestial/thumbnail.webp',
                'description'    => 'Template pernikahan premium scientific cosmic — peta langit asli pada tanggal & jam akad, dirender dari Jakarta sebagai reference point. Navy + gold + ivory, typography Cinzel + Cormorant + EB Garamond + JetBrains Mono.',
                'default_config' => [
                    'primary_color'        => '#d4af37',
                    'primary_color_light'  => '#e8e3d3',
                    'secondary_color'      => '#1a2e4a',
                    'accent_color'         => '#7d6f9b',
                    'dark_bg'              => '#0a1929',
                    'bg_color'             => '#0a1929',
                    'text_color'           => '#e8e3d3',
                    'font_title'           => 'Cinzel',
                    'font_heading'         => 'Cormorant Garamond',
                    'font_body'            => 'EB Garamond',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'events'  => ['type' => 'color', 'value' => '#1a2e4a'],
                        'gallery' => ['type' => 'color', 'value' => '#0a1929'],
                    ],

                    'ac_groom_zodiac'             => 'libra',
                    'ac_bride_zodiac'             => 'taurus',
                    'ac_show_coords'              => true,
                    'ac_show_constellation_lines' => true,
                    'ac_star_map_style'           => 'classic',
                    'ac_parallax_depth'           => 'medium',
                    'ac_twinkle_enabled'          => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ac_groom_zodiac' => 'libra',
                    'ac_bride_zodiac' => 'taurus',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 10,
            ],

            // ── Tuscany Vineyard (Premium Destination) ────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Tuscany Vineyard',
                'slug'           => 'tuscany-vineyard',
                'thumbnail_url'  => '/images/templates/tuscany-vineyard/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema Italian destination wedding — cypress horizon golden hour, ranting zaitun, terracotta tile, dan brindisi wine-glass cheers saat RSVP.',
                'default_config' => [
                    'primary_color'          => '#c97b4a',
                    'primary_color_light'    => '#f4e4c1',
                    'secondary_color'        => '#8b9d6f',
                    'accent_color'           => '#722f2f',
                    'dark_bg'                => '#3a2a1c',
                    'font_title'             => 'Italianno',
                    'font_heading'           => 'Cormorant Garamond',
                    'font_body'              => 'Crimson Text',
                    'gallery_layout'         => 'masonry',
                    'opening_style'          => 'gate',
                    'section_backgrounds'    => [
                        'events'  => ['type' => 'color', 'value' => '#fbf4e7'],
                        'rsvp'    => ['type' => 'color', 'value' => '#f4e4c1'],
                        'closing' => ['type' => 'color', 'value' => '#3a2a1c'],
                    ],
                    'tv_italian_phrases'     => true,
                    'tv_cypress_density'     => 'medium',
                    'tv_sun_flare_intensity' => 'medium',
                    'tv_wine_cheers_sound'   => true,
                    'tv_venue_landscape'     => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'          => '#c97b4a',
                    'secondary_color'        => '#8b9d6f',
                    'accent_color'           => '#722f2f',
                    'font_title'             => 'Italianno',
                    'font_heading'           => 'Cormorant Garamond',
                    'font_body'              => 'Crimson Text',
                    'tv_italian_phrases'     => true,
                    'tv_cypress_density'     => 'medium',
                    'tv_sun_flare_intensity' => 'medium',
                    'tv_wine_cheers_sound'   => true,
                    'tv_venue_landscape'     => true,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 13,
            ],

            // ── Japanese Ryokan (Premium Zen-Minimal) ────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Japanese Ryokan',
                'slug'           => 'japanese-ryokan',
                'thumbnail_url'  => '/images/templates/japanese-ryokan/thumbnail.webp',
                'description'    => 'Zen minimal Jepang — washi paper, sumi-e brush strokes, sakura petals. Indigo + cream + sakura pink. Untuk pasangan clean-aesthetic & J-culture fans.',
                'default_config' => [
                    'primary_color'        => '#1c2e4a',
                    'primary_color_light'  => '#e8b4b8',
                    'secondary_color'      => '#e8e1d3',
                    'accent_color'         => '#8c6b3f',
                    'dark_bg'              => '#0d1a30',
                    'bg_color'             => '#f3ede4',
                    'text_color'           => '#2d2d2d',
                    'text_secondary'       => '#6b6b6b',
                    'font_title'           => 'Shippori Mincho B1',
                    'font_heading'         => 'Cormorant Garamond',
                    'font_body'            => 'Noto Sans JP',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening'    => ['type' => 'color', 'value' => '#f3ede4'],
                        'couple'     => ['type' => 'color', 'value' => '#e8e1d3'],
                        'love_story' => ['type' => 'color', 'value' => '#f3ede4'],
                        'gallery'    => ['type' => 'color', 'value' => '#e8e1d3'],
                    ],
                    'ryokan_kanji_headers' => true,
                    'ryokan_kanji_dict'    => [
                        'opening'    => '序',
                        'couple'     => '二人',
                        'events'     => '祝典',
                        'countdown'  => '刻',
                        'love_story' => '物語',
                        'gallery'    => '写真',
                        'rsvp'       => '出席',
                        'gift'       => '贈物',
                        'wishes'     => '祝辞',
                        'closing'    => '結',
                    ],
                    'ryokan_petal_count'   => 5,
                    'ryokan_noren_kanji'   => '寿',
                    'ryokan_fuji_visible'  => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ryokan_kanji_headers' => true,
                    'ryokan_petal_count'   => 5,
                    'ryokan_noren_kanji'   => '寿',
                    'ryokan_fuji_visible'  => true,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 12,
            ],

            // ── Vintage Postal (Premium Storybook) ───────────────
            [
                'category_id'    => $storybook->id,
                'name'           => 'Vintage Postal',
                'slug'           => 'vintage-postal',
                'thumbnail_url'  => '/images/templates/vintage-postal/thumbnail.webp',
                'description'    => 'Template pernikahan premium bergaya kartu pos vintage — kraft paper, prangko 1950an, cap pos, mesin tik, dan rute perjalanan cinta di peta antik. Cocok untuk pasangan travel-romantic / destination wedding.',
                'default_config' => [
                    'primary_color'        => '#8b3a3a',
                    'primary_color_light'  => '#a04848',
                    'secondary_color'      => '#2c4a3e',
                    'accent_color'         => '#5c4a3a',
                    'dark_bg'              => '#3a2d1f',
                    'bg_color'             => '#e8dcc4',
                    'text_color'           => '#3a2d1f',
                    'text_secondary'       => '#5c4a3a',
                    'font_title'           => 'Special Elite',
                    'font_heading'         => 'Playfair Display',
                    'font_body'            => 'Courier Prime',
                    'font_accent'          => 'Homemade Apple',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'gate',
                    'section_backgrounds'  => new \stdClass(),

                    'vp_couple_origin_city' => 'JAKARTA',
                    'vp_postmark_dates'     => [],
                    'vp_travel_cities'      => ['JAKARTA', 'BALI', 'KYOTO', 'PARIS', 'NEW YORK'],
                    'vp_typewriter_speed'   => 'normal',
                    'vp_paper_age'          => 'medium',
                    'vp_stamp_style'        => 'vintage-1950',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'vp_couple_origin_city' => 'JAKARTA',
                    'vp_travel_cities'      => ['JAKARTA', 'BALI', 'TOKYO', 'PARIS', 'ROME'],
                    'vp_typewriter_speed'   => 'normal',
                    'vp_paper_age'          => 'medium',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 15,
            ],

            // ── Spotify Wrapped (Premium, single-flow story slides) ──
            // docs/superpowers/specs/premium-templates/spotify-wrapped-design.md
            [
                'category_id'    => $cinema->id,
                'name'           => 'Spotify Wrapped',
                'slug'           => 'spotify-wrapped',
                'thumbnail_url'  => '/images/templates/spotify-wrapped/thumbnail.svg',
                'description'    => 'Undangan single-scroll story-format — 10 slide gradient cycling ala annual recap. Couple sebagai Top Artists, love story sebagai Top Songs, event sebagai Listening Schedule. Untuk pasangan millennial/Gen-Z yang ingin undangan viral-shareable di IG Story.',
                'default_config' => [
                    'primary_color'        => '#1ED760',
                    'primary_color_light'  => '#9BFF38',
                    'secondary_color'      => '#E91D8E',
                    'accent_color'         => '#FFCB3E',
                    'dark_bg'              => '#191414',
                    'bg_color'             => '#191414',
                    'text_color'           => '#FFFFFF',
                    'text_secondary'       => 'rgba(255,255,255,0.72)',
                    'font_title'           => 'Inter',
                    'font_heading'         => 'Inter',
                    'font_body'            => 'Inter',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [],
                    'sw_year'               => '2026',
                    'sw_brand_name'         => 'TheDay Wrapped',
                    'sw_slide_order'        => ['intro', 'top-artists', 'top-songs', 'schedule', 'countdown', 'gallery', 'rsvp', 'gift', 'wishes', 'closing'],
                    'sw_gradient_intensity' => 'vivid',
                    'sw_equalizer_speed'    => 'normal',
                    'sw_show_year_bg'       => true,
                    'sw_auto_advance'       => false,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'sw_year'        => '2026',
                    'sw_brand_name'  => 'TheDay Wrapped',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 16,
            ],

            // ── Pokémon TCG (Premium, trading-card collectible) ──
            // docs/superpowers/specs/premium-templates/pokemon-tcg-design.md
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Pokémon TCG',
                'slug'           => 'pokemon-tcg',
                'thumbnail_url'  => '/images/templates/pokemon-tcg/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema trading-card collectible — holographic foil shimmer, 3D tilt, evolution chain, gym badges, energy gauge countdown. Untuk pasangan millennial/gamer yang ingin undangan playful-yet-premium. Custom 4-type system (Romantic/Tender/Joyful/Sacred) — zero trademark, zero licensed assets.',
                'default_config' => [
                    'primary_color'        => '#FFD700',
                    'primary_color_light'  => '#FFE66B',
                    'secondary_color'      => '#B8941F',
                    'accent_color'         => '#FF6B9D',
                    'dark_bg'              => '#1A1F3A',
                    'bg_color'             => '#1A1F3A',
                    'text_color'           => '#F4F1E6',
                    'text_secondary'       => '#A6A4B8',
                    'font_title'           => 'Bowlby One',
                    'font_heading'         => 'Cinzel',
                    'font_body'            => 'Inter',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'color', 'value' => '#1A1F3A'],
                        'couple'  => ['type' => 'color', 'value' => '#1A1F3A'],
                        'events'  => ['type' => 'color', 'value' => '#1A1F3A'],
                        'closing' => ['type' => 'color', 'value' => '#1A1F3A'],
                    ],
                    'tcg_groom_type'     => 'joyful',
                    'tcg_bride_type'     => 'romantic',
                    'tcg_groom_stats'    => ['love' => 180, 'loyal' => 200, 'joy' => 150],
                    'tcg_bride_stats'    => ['love' => 200, 'loyal' => 170, 'joy' => 190],
                    'tcg_edition'        => 'Wedding 1st Edition',
                    'tcg_card_number'    => '001/200',
                    'tcg_holo_intensity' => 'medium',
                    'tcg_tilt_enabled'   => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'tcg_groom_type'     => 'joyful',
                    'tcg_bride_type'     => 'romantic',
                    'tcg_holo_intensity' => 'medium',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 17,
            ],

            // ── Photo Album Old-School (Premium Storybook) ───────
            // docs/superpowers/specs/premium-templates/photo-album-design.md
            [
                'category_id'    => $storybook->id,
                'name'           => 'Photo Album Old-School',
                'slug'           => 'photo-album',
                'thumbnail_url'  => '/images/templates/photo-album/thumbnail.jpg',
                'description'    => 'Album foto fisik 1970-90an — page-flip 3D, photo corners, washi tape, caption tulisan tangan. Untuk pasangan storytelling-heavy yang ingin undangan tactile dan nostalgik.',
                'default_config' => [
                    'primary_color'        => '#d4a574',
                    'primary_color_light'  => '#e4c094',
                    'secondary_color'      => '#8b6f47',
                    'accent_color'         => '#5a3818',
                    'dark_bg'              => '#1a1410',
                    'bg_color'             => '#1a1410',
                    'text_color'           => '#f4ead5',
                    'text_secondary'       => '#c9bfa8',
                    'font_title'           => 'Pinyon Script',
                    'font_heading'         => 'Cormorant SC',
                    'font_body'            => 'Crimson Text',
                    'font_accent'          => 'Homemade Apple',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => new \stdClass(),

                    'pa_cover_photo'       => null,
                    'pa_cover_title'       => 'Our Wedding Album 2026',
                    'pa_page_aging'        => 'medium',
                    'pa_washi_pattern'     => 'mixed',
                    'pa_pressed_flower'    => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'pa_cover_title'    => 'Ahmad & Siti — Album 2026',
                    'pa_page_aging'     => 'medium',
                    'pa_washi_pattern'  => 'mixed',
                    'pa_pressed_flower' => true,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 18,
            ],

            // ── Dark Room Flashlight (Premium Experiential) ──────
            // docs/superpowers/specs/premium-templates/flashlight-design.md
            [
                'category_id'    => $cinema->id,
                'name'           => 'Dark Room Flashlight',
                'slug'           => 'flashlight',
                'thumbnail_url'  => '/images/templates/flashlight/thumbnail.webp',
                'description'    => 'Template pernikahan premium experiential — kanvas pitch black yang harus dijelajahi pakai senter (radial mask follow cursor / drag). Section disebar di koordinat 2D dan ditemukan satu per satu lewat eksplorasi non-linear. Mood film noir cinematic, romantik misterius.',
                'default_config' => [
                    'primary_color'        => '#C9A961',
                    'primary_color_light'  => '#FFD580',
                    'secondary_color'      => '#A02E1B',
                    'accent_color'         => '#F2C4B8',
                    'dark_bg'              => '#000000',
                    'bg_color'             => '#000000',
                    'text_color'           => '#F5E6CC',
                    'text_secondary'       => '#8A7B6A',

                    'font_title'           => 'Cormorant Garamond',
                    'font_heading'         => 'Cinzel',
                    'font_body'            => 'EB Garamond',
                    'font_accent'          => 'Italianno',

                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',

                    'section_backgrounds'  => [
                        'opening' => ['type' => 'color', 'value' => '#000000'],
                        'couple'  => ['type' => 'color', 'value' => '#000000'],
                        'events'  => ['type' => 'color', 'value' => '#000000'],
                        'closing' => ['type' => 'color', 'value' => '#000000'],
                    ],

                    'fl_beam_radius'        => 'medium',
                    'fl_beam_warmth'        => 'warm',
                    'fl_minimap_visible'    => true,
                    'fl_dust_motes_enabled' => true,
                    'fl_section_layout'     => 'scatter',
                    'fl_section_positions'  => new \stdClass(),
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'fl_beam_radius'        => 'medium',
                    'fl_beam_warmth'        => 'warm',
                    'fl_minimap_visible'    => true,
                    'fl_dust_motes_enabled' => true,
                    'fl_section_layout'     => 'scatter',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 19,
            ],

            // ── Pop-up Card (Premium, paper-engineering artisan) ─
            // docs/superpowers/specs/premium-templates/popup-card-design.md
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Pop-up Card',
                'slug'           => 'popup-card',
                'thumbnail_url'  => '/images/templates/popup-card/thumbnail.webp',
                'description'    => 'Template pernikahan premium ber-tema kartu pop-up artisan — buka kartu di tengah layar, lalu setiap scene berdiri seperti diorama kertas 3D dengan layered cutout, fold-line, dan confetti pada momen perayaan. Untuk pasangan yang ingin undangan terasa seperti hadiah handmade, bukan poster digital.',
                'default_config' => [
                    'primary_color'        => '#d4af37',
                    'primary_color_light'  => '#f3e5a0',
                    'secondary_color'      => '#b73e3e',
                    'accent_color'         => '#d4af37',
                    'dark_bg'              => '#2c3e50',
                    'bg_color'             => '#f9f1e3',
                    'text_color'           => '#3a2e21',
                    'text_secondary'       => '#7a6a55',
                    'font_title'           => 'Bodoni Moda',
                    'font_heading'         => 'Cormorant SC',
                    'font_body'            => 'Crimson Text',
                    'font_accent'          => 'Pinyon Script',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'paper', 'value' => 'cream'],
                        'couple'  => ['type' => 'paper', 'value' => 'cream'],
                        'events'  => ['type' => 'paper', 'value' => 'cream'],
                        'closing' => ['type' => 'paper', 'value' => 'cream'],
                    ],
                    'pc_paper_color'              => 'cream',
                    'pc_confetti_burst_on_scenes' => ['countdown', 'rsvp', 'closing'],
                    'pc_ambient_sparkle'          => true,
                    'pc_layer_depth_intensity'    => 'medium',
                    'pc_venue_silhouette'         => 'church',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'pc_paper_color'              => 'cream',
                    'pc_confetti_burst_on_scenes' => ['countdown', 'rsvp', 'closing'],
                    'pc_ambient_sparkle'          => true,
                    'pc_layer_depth_intensity'    => 'medium',
                    'pc_venue_silhouette'         => 'church',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 20,
            ],

            // ── Silk Veil (Premium, bridal-luxe veil-reveal) ──────────────────────
            // docs/superpowers/specs/premium-templates/silk-veil-design.md
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Silk Veil',
                'slug'           => 'silk-veil',
                'thumbnail_url'  => '/images/templates/silk-veil/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema kerudung pengantin — setiap section tertutup veil sutra semi-transparan yang disibak via drag horizontal atau tap. Single-flow scrollable feed dengan lace Victorian, mutiara, dan filigree emas. Cocok untuk pasangan bridal-traditional / luxe-romantic / classic-wedding.',
                'default_config' => [
                    'primary_color'        => '#C9A961',
                    'primary_color_light'  => '#F8E0DC',
                    'secondary_color'      => '#D4A5A5',
                    'accent_color'         => '#C9A961',
                    'dark_bg'              => '#FAFAF5',
                    'bg_color'             => '#FAFAF5',
                    'text_color'           => '#3D3530',
                    'text_secondary'       => '#7A6F65',
                    'font_title'           => 'Italianno',
                    'font_heading'         => 'Cormorant SC',
                    'font_body'            => 'EB Garamond',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'color', 'value' => '#FAFAF5'],
                        'couple'  => ['type' => 'color', 'value' => '#FAFAF5'],
                        'events'  => ['type' => 'color', 'value' => '#F2E9DC'],
                        'gift'    => ['type' => 'color', 'value' => '#F2E9DC'],
                        'closing' => ['type' => 'color', 'value' => '#FAFAF5'],
                    ],
                    'sv_veil_color'           => 'white',
                    'sv_lace_density'         => 'medium',
                    'sv_pearl_decor'          => 'edges',
                    'sv_auto_part_on_scroll'  => false,
                    'sv_remember_state'       => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'sv_veil_color'    => 'white',
                    'sv_lace_density'  => 'medium',
                    'sv_pearl_decor'   => 'edges',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 21,
            ],

            // ── Snow Globe (Premium Whimsical Winter) ───────────────
            // docs/superpowers/specs/premium-templates/snow-globe-design.md
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Snow Globe',
                'slug'           => 'snow-globe',
                'thumbnail_url'  => '/images/templates/snow-globe/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema bola salju ajaib — globe kaca interaktif yang bisa di-tap, di-shake, dan merespons gyroscope. Setiap section adegan berbeda di dalam globe (gerbang sambutan, hourglass, polaroid, treasure chest, dst). Untuk pasangan winter / holiday-romantic.',
                'default_config' => [
                    'primary_color'        => '#C9A961',
                    'primary_color_light'  => '#F4E4C1',
                    'secondary_color'      => '#A4C5DB',
                    'accent_color'         => '#C9A961',
                    'dark_bg'              => '#050813',
                    'bg_color'             => '#050813',
                    'text_color'           => '#FAFAF5',
                    'text_secondary'       => '#D8DAE0',
                    'font_title'           => 'Cormorant Garamond',
                    'font_heading'         => 'Cinzel',
                    'font_body'            => 'EB Garamond',
                    'font_accent'          => 'Italianno',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'color', 'value' => '#050813'],
                        'couple'  => ['type' => 'color', 'value' => '#050813'],
                        'closing' => ['type' => 'color', 'value' => '#050813'],
                    ],
                    'sg_snow_density'  => 'medium',
                    'sg_globe_size'    => 'medium',
                    'sg_gyro_enabled'  => true,
                    'sg_music_chime'   => true,
                    'sg_default_scene' => 'opening',
                    'sg_base_material' => 'wood',
                    'sg_monogram_text' => 'A & B',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'sg_snow_density'  => 'medium',
                    'sg_globe_size'    => 'medium',
                    'sg_default_scene' => 'opening',
                    'sg_base_material' => 'wood',
                    'sg_monogram_text' => 'A & S',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 22,
            ],

            // ── Vinyl Record (Premium, retro luxe turntable navigation) ──
            // docs/superpowers/specs/premium-templates/vinyl-record-design.md
            [
                'category_id'    => $cinema->id,
                'name'           => 'Vinyl Record',
                'slug'           => 'vinyl-record',
                'thumbnail_url'  => '/images/templates/vinyl-record/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema retro luxe vinyl turntable. Sleeve cover di awal, lalu turntable kayu walnut dengan piringan hitam yang berputar, tonearm yang mendarat di tiap track. 12 momen pernikahan terbagi Side A/B yang flip-able. Untuk pasangan 30-45 kolektor vinyl, audiophile, atau kurator musik. Palette walnut + brass + cream label, font Bebas Neue + DM Serif Display.',
                'default_config' => [
                    'primary_color'        => '#B8902F',
                    'primary_color_light'  => '#D4AA42',
                    'secondary_color'      => '#5C3A21',
                    'accent_color'         => '#C73E3A',
                    'dark_bg'              => '#0a0a0a',
                    'bg_color'             => '#0a0a0a',
                    'text_color'           => '#F5E6CC',
                    'text_secondary'       => '#D8C8A8',
                    'font_title'           => 'Bebas Neue',
                    'font_heading'         => 'DM Serif Display',
                    'font_body'            => 'Inter',
                    'font_accent'          => 'Bree Serif',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening'  => ['type' => 'color', 'value' => '#F5E6CC'],
                        'couple'   => ['type' => 'color', 'value' => '#F5E6CC'],
                        'closing'  => ['type' => 'color', 'value' => '#0a0a0a'],
                    ],
                    'vr_album_title'      => 'THE WEDDING SESSIONS',
                    'vr_label_color'      => 'red',
                    'vr_year'             => '2026',
                    'vr_side_split'       => 'auto',
                    'vr_audio_autoplay'   => false,
                    'vr_grain_intensity'  => 'subtle',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'vr_album_title'     => 'THE WEDDING SESSIONS',
                    'vr_label_color'     => 'red',
                    'vr_year'            => '2026',
                    'vr_grain_intensity' => 'subtle',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 23,
            ],

            // ── Year Scrubber (Premium Editorial) ─────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Year Scrubber',
                'name_en'        => 'Year Scrubber',
                'slug'           => 'year-scrubber',
                'thumbnail_url'  => '/images/templates/year-scrubber/thumbnail.jpg',
                'description'    => 'Template undangan premium dengan interactive timeline scrubber — geser garis waktu dari tahun pertama bertemu hingga tahun pernikahan, milestone foto crossfade per tahun, dan section setelah hari-H (events, countdown, RSVP, gift, wishes) unveil saat scrubber mencapai tahun akad. Identitas: Bebas Neue raksasa + Cormorant + JetBrains Mono. Catatan: ganti font_title akan mempengaruhi tampilan tahun raksasa.',
                'default_config' => [
                    'primary_color'         => '#1A2E4A',
                    'primary_color_light'   => '#2A4063',
                    'secondary_color'       => '#C9A961',
                    'accent_color'          => '#E8B4B8',
                    'dark_bg'               => '#1A2E4A',
                    'bg_color'              => '#FAF8F2',
                    'text_color'            => '#1A2E4A',
                    'text_secondary'        => '#A39E94',
                    'font_title'            => 'Bebas Neue',
                    'font_heading'          => 'Cormorant Garamond',
                    'font_body'             => 'EB Garamond',
                    'gallery_layout'        => 'grid',
                    'opening_style'         => 'fade',
                    'section_backgrounds'   => [
                        'opening'    => ['type' => 'color', 'value' => '#FAF8F2'],
                        'couple'     => ['type' => 'color', 'value' => '#F5F0E8'],
                        'events'     => ['type' => 'color', 'value' => '#FAF8F2'],
                        'countdown'  => ['type' => 'color', 'value' => '#F5F0E8'],
                        'love_story' => ['type' => 'color', 'value' => '#FAF8F2'],
                        'closing'    => ['type' => 'color', 'value' => '#F5F0E8'],
                    ],
                    'ys_start_year'             => null,
                    'ys_end_year'               => null,
                    'ys_autoplay_duration'      => 12000,
                    'ys_intensity_graph'        => true,
                    'ys_milestone_dot_size'     => 'medium',
                    'ys_bg_gradient_intensity'  => 'medium',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ys_autoplay_duration'     => 12000,
                    'ys_intensity_graph'       => true,
                    'ys_milestone_dot_size'    => 'medium',
                    'ys_bg_gradient_intensity' => 'medium',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 24,
            ],

            // ── IG Stories (Premium Pop-Culture, tap-zone story deck) ──
            // Legal: brand-safe adaptation of the public vertical-ephemeral story-deck UX format.
            // NO Instagram logo, NO Helvetica / Instagram Sans, NO Meta wordmark. Default brand mark
            // rendered to users is "TheDay". See docs/superpowers/specs/premium-templates/ig-stories-design.md
            [
                'category_id'    => $cinema->id,
                'name'           => 'IG Stories',
                'slug'           => 'ig-stories',
                'thumbnail_url'  => '/images/templates/ig-stories/thumbnail.webp',
                'description'    => 'Undangan tap-zone story-deck format — 10 story full-screen vertical 9:16 dengan progress bars, auto-advance, swipe gesture, dan sticker interaktif (poll RSVP, question wishes, countdown). Untuk pasangan Gen-Z & millennial yang ingin undangan viral-shareable mobile-native.',
                'default_config' => [
                    'primary_color'        => '#833ab4',
                    'primary_color_light'  => '#fcb045',
                    'secondary_color'      => '#fd1d1d',
                    'accent_color'         => '#FFFFFF',
                    'dark_bg'              => '#000000',
                    'bg_color'             => '#000000',
                    'text_color'           => '#FFFFFF',
                    'text_secondary'       => 'rgba(255,255,255,0.72)',
                    'font_title'           => 'Inter',
                    'font_heading'         => 'Inter',
                    'font_body'            => 'Inter',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening'    => ['type' => 'gradient', 'value' => 'sunset'],
                        'couple'     => ['type' => 'photo',    'value' => 'cover'],
                        'love_story' => ['type' => 'gradient', 'value' => 'pastel-pink'],
                        'events'     => ['type' => 'gradient', 'value' => 'blue-cyan'],
                        'countdown'  => ['type' => 'gradient', 'value' => 'red-urgent'],
                        'gallery'    => ['type' => 'collage',  'value' => 'grid'],
                        'rsvp'       => ['type' => 'gradient', 'value' => 'soft-poll'],
                        'gift'       => ['type' => 'gradient', 'value' => 'gold-swipe'],
                        'wishes'     => ['type' => 'gradient', 'value' => 'mint-question'],
                        'closing'    => ['type' => 'gradient', 'value' => 'sunset-cycle'],
                    ],
                    'ig_username'          => 'thedaywedding',
                    'ig_avatar_ring_style' => 'gradient',
                    'ig_story_duration'    => 6,
                    'ig_auto_advance'      => true,
                    'ig_story_order'       => ['opening','couple','love_story','events','countdown','gallery','rsvp','gift','wishes','closing'],
                    'ig_brand_name'        => 'TheDay',
                    'ig_show_overview'     => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ig_username'   => 'thedaywedding',
                    'ig_brand_name' => 'TheDay',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 25,
            ],

            // ── Treasure Hunt (Premium Storybook) ──────────────────
            // docs/superpowers/specs/premium-templates/treasure-hunt-design.md
            [
                'category_id'    => $storybook->id,
                'name'           => 'Treasure Hunt',
                'slug'           => 'treasure-hunt',
                'thumbnail_url'  => '/images/templates/treasure-hunt/thumbnail.webp',
                'description'    => 'Template premium pan-and-zoom — gulungan kulit lapuk menjadi peta interaktif "Isle of Matrimony" dengan 12 X-mark POI menggantikan section card konvensional. Untuk pasangan adventure-loving / destination wedding.',
                'default_config' => [
                    'primary_color'        => '#8B1A1F',
                    'primary_color_light'  => '#A02E1B',
                    'secondary_color'      => '#C9A961',
                    'accent_color'         => '#C9A961',
                    'dark_bg'              => '#3D2817',
                    'bg_color'             => '#E8D5A0',
                    'text_color'           => '#3D2817',
                    'text_secondary'       => '#6B4F38',
                    'font_title'           => 'IM Fell English',
                    'font_heading'         => 'Cinzel',
                    'font_body'            => 'Crimson Text',
                    'font_accent'          => 'Pirata One',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [],
                    'th_couple_initials'   => 'A & B',
                    'th_island_name'       => 'Isle of Matrimony',
                    'th_route_revealed'    => true,
                    'th_sea_monsters'      => ['kraken', 'mermaid', 'serpent', 'whale'],
                    'th_compass_style'     => 'classic',
                    'th_zoom_default'      => 1.0,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'th_couple_initials'   => 'A & B',
                    'th_island_name'       => 'Isle of Matrimony',
                    'th_route_revealed'    => true,
                    'th_sea_monsters'      => ['kraken', 'mermaid', 'serpent', 'whale'],
                    'th_compass_style'     => 'classic',
                    'th_zoom_default'      => 1.0,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 26,
            ],

            // ── Comic Book Strip (Premium, swipe-deck pop-art) ──────────────
            [
                'category_id'    => $cinema->id,
                'name'           => 'Comic Book Strip',
                'slug'           => 'comic-book',
                'thumbnail_url'  => '/images/templates/comic-book/thumbnail.webp',
                'description'    => 'Undangan pernikahan premium bertema komik vintage Minggu pagi — 10 halaman komik multi-panel, Ben-Day halftone, speech bubble, dan ledakan BAM!/POW!/BOOM! di tiap halaman. Swipe horizontal seperti membalik komik fisik. Untuk pasangan millennial/Gen-Z pencinta pop-culture & comic-enthusiast.',
                'default_config' => [
                    'primary_color'       => '#E63946',
                    'primary_color_light' => '#FCE7E9',
                    'secondary_color'     => '#1D3557',
                    'accent_color'        => '#F1C453',
                    'dark_bg'             => '#0A0A0A',
                    'bg_color'            => '#F9F4E2',
                    'text_color'          => '#0A0A0A',
                    'text_secondary'      => '#5A5A5A',
                    'font_title'          => 'Bangers',
                    'font_heading'        => 'Bowlby One',
                    'font_body'           => 'Comic Neue',
                    'gallery_layout'      => 'grid',
                    'opening_style'       => 'fade',
                    'section_backgrounds' => [
                        'opening'   => ['type' => 'paper',    'value' => 'cream'],
                        'couple'    => ['type' => 'halftone', 'value' => 'medium-blue'],
                        'events'    => ['type' => 'color',    'value' => '#F9F4E2'],
                        'countdown' => ['type' => 'halftone', 'value' => 'dense-yellow'],
                        'closing'   => ['type' => 'paper',    'value' => 'cream'],
                    ],
                    'cb_issue_number'    => '001',
                    'cb_cover_title'     => 'THE WEDDING',
                    'cb_cover_price'     => 'Rp25.000',
                    'cb_color_scheme'    => 'primary',
                    'cb_panel_density'   => 'medium',
                    'cb_sound_effects'   => true,
                    'cb_pencil_hatching' => true,
                    'cb_page_turn_3d'    => false,
                    'cb_groom_quote'     => 'Time to suit up!',
                    'cb_bride_quote'     => "Let's do this!",
                    'cb_closing_teaser'  => 'On sale forever!',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'cb_issue_number' => '001',
                    'cb_cover_title'  => 'THE WEDDING',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 27,
            ],

            // ── Tarot Reading (Premium, mystical card reveal) ──
            // docs/superpowers/specs/premium-templates/tarot-reading-design.md
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Tarot Reading',
                'slug'           => 'tarot-reading',
                'thumbnail_url'  => '/images/templates/tarot-reading/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema pembacaan tarot mistis-romantis — 12 kartu Wedding Arcana custom dengan 3D flip reveal, holographic foil shimmer, dan mystical aura particles.',
                'default_config' => [
                    'primary_color'        => '#D4AF37',
                    'primary_color_light'  => '#F3E5A0',
                    'secondary_color'      => '#9B8327',
                    'accent_color'         => '#8B5CF6',
                    'dark_bg'              => '#0F0B23',
                    'bg_color'             => '#0F0B23',
                    'text_color'           => '#F5E6D3',
                    'text_secondary'       => '#9D8FB0',
                    'font_title'           => 'Cormorant Garamond',
                    'font_heading'         => 'Cinzel Decorative',
                    'font_body'            => 'EB Garamond',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'color', 'value' => '#0F0B23'],
                        'couple'  => ['type' => 'color', 'value' => '#0F0B23'],
                        'events'  => ['type' => 'color', 'value' => '#0F0B23'],
                        'closing' => ['type' => 'color', 'value' => '#0F0B23'],
                    ],
                    'tr_spread_layout'     => 'arc',
                    'tr_card_count'        => 12,
                    'tr_holo_intensity'    => 'medium',
                    'tr_aura_enabled'      => true,
                    'tr_mystical_theme'    => 'midnight',
                    'tr_monogram_text'     => 'G & B',
                    'tr_allow_toggle_back' => false,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'tr_spread_layout'  => 'arc',
                    'tr_holo_intensity' => 'medium',
                    'tr_mystical_theme' => 'midnight',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 28,
            ],
        ];

        foreach ($templates as $template) {
            Template::updateOrCreate(['slug' => $template['slug']], $template);
        }

        // Remove leftover birthday templates
        Template::whereIn('slug', ['confetti-ceria', 'biru-bintang', 'peach-balon'])->delete();
    }
}
