<?php

// database/seeders/TemplateSeeder.php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Template;
use App\Models\TemplateCategory;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $pernikahan = TemplateCategory::where('slug', 'pernikahan')->firstOrFail();
        $storybook  = TemplateCategory::where('slug', 'storybook')->firstOrFail();
        $cinema     = TemplateCategory::where('slug', 'cinema')->firstOrFail();

        $weddingDemo = [
            'details' => [
                'groom_name'         => 'Ahmad Rizky',
                'bride_name'         => 'Siti Nurhaliza',
                'groom_photo_url'    => '/image/demo-image/groom.png',
                'bride_photo_url'    => '/image/demo-image/bride.png',
                'groom_parent_names' => 'Bpk. Hasan & Ibu Fatimah',
                'bride_parent_names' => 'Bpk. Rahmat & Ibu Aminah',
                'groom_instagram'    => 'ahmadrizky',
                'bride_instagram'    => 'sitinurhaliza',
                'opening_text'       => "Bismillahirrahmanirrahim\nDengan memohon rahmat dan ridho Allah SWT, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri pernikahan kami.",
                'closing_text'       => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.',
            ],
            'events' => [
                [
                    'event_name'    => 'Akad Nikah',
                    'event_date'    => '2026-06-15',
                    'start_time'    => '08:00',
                    'end_time'      => '10:00',
                    'venue_name'    => 'Masjid Al-Ikhlas',
                    'venue_address' => 'Jl. Sudirman No. 123, Jakarta Selatan',
                    'maps_url'      => 'https://maps.google.com/?q=-6.2088,106.8456',
                ],
                [
                    'event_name'    => 'Resepsi',
                    'event_date'    => '2026-06-15',
                    'start_time'    => '11:00',
                    'end_time'      => '14:00',
                    'venue_name'    => 'Ballroom Hotel Mulia',
                    'venue_address' => 'Jl. Asia Afrika No. 8, Jakarta Selatan',
                    'maps_url'      => 'https://maps.google.com/?q=-6.2150,106.8070',
                ],
            ],
            'gallery' => [
                '/image/demo-image/galeri/galeri-0.webp',
                '/image/demo-image/galeri/galeri-1.webp',
                '/image/demo-image/galeri/galeri-0.webp',
                '/image/demo-image/galeri/galeri-1.webp',
            ],
            'gift' => [
                'accounts' => [
                    ['bank' => 'BCA',      'account_number' => '1234567890', 'account_name' => 'Ahmad Rizky'],
                    ['bank' => 'Mandiri',  'account_number' => '0987654321', 'account_name' => 'Siti Nurhaliza'],
                ],
            ],
            'love_story' => [
                [
                    'date'        => 'Maret 2020',
                    'title'       => 'Pertama Bertemu',
                    'description' => 'Kami pertama kali bertemu di sebuah seminar kampus. Satu tatapan yang tak terlupakan menjadi awal dari segalanya.',
                ],
                [
                    'date'        => 'Juni 2020',
                    'title'       => 'Jatuh Hati',
                    'description' => 'Setelah beberapa bulan sering menghabiskan waktu bersama, kami sadar ada sesuatu yang istimewa di antara kami.',
                ],
                [
                    'date'        => 'Desember 2021',
                    'title'       => 'Resmi Bersama',
                    'description' => 'Di bawah langit berbintang, Ahmad memberanikan diri mengungkapkan perasaannya. Siti pun menerima dengan senyum termanis.',
                ],
                [
                    'date'        => 'Juni 2026',
                    'title'       => 'Menuju Pelaminan',
                    'description' => 'Dengan restu kedua keluarga dan doa dari orang-orang tercinta, kami siap melangkah ke babak baru kehidupan bersama.',
                ],
            ],
        ];

        $templates = [
            // ── Pernikahan ─────────────────────────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Bunga Abadi',
                'slug'           => 'bunga-abadi',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan elegan dengan sentuhan bunga dan nuansa hangat keemasan.',
                'default_config' => [
                    'primary_color'   => '#D4A373',
                    'secondary_color' => '#FEFAE0',
                    'accent_color'    => '#CCD5AE',
                    'font_title'      => 'Playfair Display',
                    'font_body'       => 'Poppins',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'fade-up',
                    'bg_pattern'      => 'floral',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#D4A373',
                    'secondary_color' => '#FEFAE0',
                    'font_title'      => 'Playfair Display',
                    'font_body'       => 'Poppins',
                ]]),
                'tier'           => 'free',
                'is_active'      => true,
                'sort_order'     => 1,
            ],
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Langit Senja',
                'slug'           => 'langit-senja',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan romantis dengan palet warna sunset yang memukau.',
                'default_config' => [
                    'primary_color'   => '#E57070',
                    'secondary_color' => '#FDE8E8',
                    'accent_color'    => '#F4A261',
                    'font_title'      => 'Cormorant Garamond',
                    'font_body'       => 'Lato',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'slide-up',
                    'bg_pattern'      => 'watercolor',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#E57070',
                    'secondary_color' => '#FDE8E8',
                    'font_title'      => 'Cormorant Garamond',
                    'font_body'       => 'Lato',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 2,
            ],
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Hijau Daun',
                'slug'           => 'hijau-daun',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan segar dengan nuansa alam dan dedaunan hijau.',
                'default_config' => [
                    'primary_color'   => '#52796F',
                    'secondary_color' => '#CAD2C5',
                    'accent_color'    => '#84A98C',
                    'font_title'      => 'DM Serif Display',
                    'font_body'       => 'Nunito',
                    'layout'          => 'vertical-scroll',
                    'animation'       => 'fade-in',
                    'bg_pattern'      => 'leaves',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'   => '#52796F',
                    'secondary_color' => '#CAD2C5',
                    'font_title'      => 'DM Serif Display',
                    'font_body'       => 'Nunito',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 3,
            ],

            // ── Storybook (scene/illustrated templates) ────────────
            [
                'category_id'    => $storybook->id,
                'name'           => 'Beach',
                'slug'           => 'beach',
                'thumbnail_url'  => '/images/templates/beach/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya pantai tropis — jelajahi setiap bagian undangan layaknya petualangan seru di tepi laut.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 5,
            ],
            [
                'category_id'    => $storybook->id,
                'name'           => 'Garden',
                'slug'           => 'garden',
                'thumbnail_url'  => '/images/templates/garden/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya taman bunga yang hidup — temukan setiap detail undangan di antara hamparan bunga dan pepohonan yang rimbun.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 6,
            ],
            [
                'category_id'    => $storybook->id,
                'name'           => 'Night Sky',
                'slug'           => 'night-sky',
                'thumbnail_url'  => '/images/templates/night-sky/thumbnail.webp',
                'description'    => 'Template pernikahan interaktif bergaya langit malam berbintang — rayakan cinta di bawah ribuan bintang yang berkelip memukau.',
                'default_config' => [],
                'demo_data'      => $weddingDemo,
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 7,
            ],

            // ── Nusantara (Premium, dedicated renderer) ───────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Nusantara',
                'slug'           => 'nusantara',
                'thumbnail_url'  => null,
                'description'    => 'Template pernikahan premium bergaya keraton Jawa — megah, sakral, dan agung. Dilengkapi animasi gapura, ornamen batik kawung, sulur lung-lungan, dan mandala teratai.',
                'default_config' => [
                    'primary_color'       => '#8B6914',
                    'primary_color_light' => '#C9A84C',
                    'secondary_color'     => '#F5F0E8',
                    'accent_color'        => '#6B1D1D',
                    'dark_bg'             => '#2C1810',
                    'font_title'          => 'Cinzel Decorative',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Crimson Text',
                    'layout'              => 'vertical-scroll',
                    'animation'           => 'javanese-gate',
                    'has_opening_animation' => true,
                    'has_parallax'          => true,
                    'has_countdown'         => true,
                    'ornament_style'        => 'javanese',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'       => '#8B6914',
                    'primary_color_light' => '#C9A84C',
                    'secondary_color'     => '#F5F0E8',
                    'accent_color'        => '#6B1D1D',
                    'dark_bg'             => '#2C1810',
                    'font_title'          => 'Cinzel Decorative',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Crimson Text',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 4,
            ],

            // ── Onyx Noir (Premium Luxury) ───────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Onyx Noir',
                'slug'           => 'onyx-noir',
                'thumbnail_url'  => '/images/templates/onyx-noir/thumbnail.webp',
                'description'    => 'Template pernikahan premium dark luxury — marmer hitam carrara, aksen gold leaf, dan wax seal yang pecah di tap pertama. Untuk pasangan yang menginginkan kesan museum-quality, formal-sophisticated, tanpa flora-fauna.',
                'default_config' => [
                    'primary_color'        => '#d4af37',
                    'primary_color_light'  => '#f3e5a0',
                    'secondary_color'      => '#b8941f',
                    'accent_color'         => '#d4af37',
                    'dark_bg'              => '#0a0a0a',
                    'bg_color'             => '#0a0a0a',
                    'text_color'           => '#f5f5f0',
                    'text_secondary'       => '#a8a8a8',
                    'font_title'           => 'Cormorant Garamond',
                    'font_heading'         => 'Tenor Sans',
                    'font_body'            => 'Inter',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening' => ['type' => 'marble', 'value' => 'subtle'],
                        'couple'  => ['type' => 'marble', 'value' => 'subtle'],
                        'events'  => ['type' => 'color',  'value' => '#0a0a0a'],
                        'closing' => ['type' => 'marble', 'value' => 'strong'],
                    ],
                    'onyx_monogram_text'    => 'A & B',
                    'onyx_seal_motif'       => 'geometric',
                    'onyx_marble_intensity' => 'subtle',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'onyx_monogram_text'    => 'A & S',
                    'onyx_seal_motif'       => 'geometric',
                    'onyx_marble_intensity' => 'subtle',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 9,
            ],

            // ── Cinema ────────────────────────────────────────────
            [
                'category_id'    => $cinema->id,
                'name'           => 'Netflix',
                'slug'           => 'netflix',
                'thumbnail_url'  => null,
                'description'    => 'Template undangan pernikahan bertema Netflix — cinematic, bold, dan ikonik. Tamu diajak masuk lewat layar "Who\'s Watching?" sebelum menikmati undangan seperti sebuah Netflix Original.',
                'default_config' => [
                    'netflix_subtitle' => 'Sebuah Kisah Cinta',
                    'netflix_tags'     => ['#lovestory', '#romantic', '#halal', '#forever'],
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'netflix_subtitle' => 'Sebuah Kisah Cinta',
                    'netflix_tags'     => ['#lovestory', '#romantic', '#halal', '#forever'],
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 8,
            ],

            // ── Art Deco Gatsby (Premium, multi-phase orchestrator) ─
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Art Deco Gatsby',
                'slug'           => 'art-deco-gatsby',
                'thumbnail_url'  => '/templates/art-deco-gatsby-thumb.jpg',
                'description'    => 'Opulent 1920s Gatsby — gold sunburst on near-black, chevron borders, fan motifs. Timeless luxury.',
                'default_config' => [
                    'primary_color'       => '#c9a961',
                    'primary_color_light' => '#f4ead5',
                    'secondary_color'     => '#1a3a2e',
                    'accent_color'        => '#c9a961',
                    'dark_bg'             => '#0d0d0d',
                    'font_title'          => 'Poiret One',
                    'font_heading'        => 'Cormorant Garamond',
                    'font_body'           => 'Lato',
                    'gallery_layout'      => 'grid',
                    'opening_style'       => 'fade',
                    'section_backgrounds' => [
                        'events'    => ['type' => 'color', 'value' => '#0d0d0d'],
                        'countdown' => ['type' => 'color', 'value' => '#1a1a1a'],
                    ],
                    'deco_monogram'        => 'auto',
                    'deco_sunburst_rays'   => 24,
                    'deco_accent_color'    => 'gold',
                    'deco_chevron_density' => 'medium',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'  => '#c9a961',
                    'dark_bg'        => '#0d0d0d',
                    'font_title'     => 'Poiret One',
                    'font_heading'   => 'Cormorant Garamond',
                    'font_body'      => 'Lato',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 9,
            ],

            // ── Velvet Burgundy (Premium, dedicated renderer) ─────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Velvet Burgundy',
                'slug'           => 'velvet-burgundy',
                'thumbnail_url'  => '/templates/velvet-burgundy-thumb.jpg',
                'description'    => 'Undangan premium Victorian-modern: beludru maroon + filigree emas + segel lilin. Cocok untuk warna hangat klasik (akad/resepsi adat-modern).',
                'default_config' => [
                    'primary_color'           => '#5c1a1b',
                    'primary_color_light'     => '#8b1a1f',
                    'secondary_color'         => '#d4a574',
                    'accent_color'            => '#a87a4a',
                    'dark_bg'                 => '#3a0c0e',
                    'font_title'              => 'Playfair Display',
                    'font_heading'            => 'Cormorant SC',
                    'font_body'               => 'Crimson Text',
                    'gallery_layout'          => 'masonry',
                    'opening_style'           => 'fade',
                    'velvet_seal_monogram'    => 'A & S',
                    'velvet_seal_motif'       => 'rose',
                    'velvet_filigree_density' => 'medium',
                    'velvet_paper_panels'     => true,
                    'velvet_cover_subtitle'   => 'Sebuah Undangan Pernikahan',
                    'section_backgrounds'     => [
                        'events' => ['type' => 'color', 'value' => '#3a0c0e'],
                        'rsvp'   => ['type' => 'image', 'value' => '/images/templates/velvet-burgundy/paper-cream.webp'],
                        'gift'   => ['type' => 'image', 'value' => '/images/templates/velvet-burgundy/paper-cream.webp'],
                    ],
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'         => '#5c1a1b',
                    'secondary_color'       => '#d4a574',
                    'accent_color'          => '#a87a4a',
                    'dark_bg'               => '#3a0c0e',
                    'font_title'            => 'Playfair Display',
                    'font_heading'          => 'Cormorant SC',
                    'font_body'             => 'Crimson Text',
                    'velvet_seal_monogram'  => 'A & S',
                    'velvet_cover_subtitle' => 'Sebuah Undangan Pernikahan',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 14,
            ],

            // ── Belle Époque Parisian (Premium, watercolor multi-phase) ──
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Belle Époque Parisian',
                'slug'           => 'belle-epoque',
                'thumbnail_url'  => '/images/templates/belle-epoque/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema café Paris era Belle Époque — watercolor Eiffel, peony hand-painted, tipografi script tulisan tangan, dan postcard motif.',
                'default_config' => [
                    'primary_color'       => '#d4a5a5',
                    'primary_color_light' => '#fdf6ed',
                    'secondary_color'     => '#b8860b',
                    'accent_color'        => '#7a9b8e',
                    'dark_bg'             => '#3d3d3d',
                    'font_title'          => 'Italianno',
                    'font_heading'        => 'Cormorant SC',
                    'font_body'           => 'EB Garamond',
                    'gallery_layout'      => 'masonry',
                    'opening_style'       => 'fade',
                    'section_backgrounds' => [
                        'events'     => ['type' => 'color', 'value' => '#fdf6ed'],
                        'love_story' => ['type' => 'color', 'value' => '#fdf6ed'],
                        'gift'       => ['type' => 'color', 'value' => '#f7e9dc'],
                    ],
                    'bp_couple_initials'  => 'A & B',
                    'bp_postcard_city'    => 'JAKARTA',
                    'bp_destination_city' => 'PARIS',
                    'bp_floral_palette'   => 'mixed',
                    'bp_eiffel_visible'   => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'       => '#d4a5a5',
                    'primary_color_light' => '#fdf6ed',
                    'secondary_color'     => '#b8860b',
                    'accent_color'        => '#7a9b8e',
                    'font_title'          => 'Italianno',
                    'font_heading'        => 'Cormorant SC',
                    'font_body'           => 'EB Garamond',
                    'bp_postcard_city'    => 'JAKARTA',
                    'bp_destination_city' => 'PARIS',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 11,
            ],

            // ── Astronomy Celestial (Premium) ────────────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Astronomy Celestial',
                'slug'           => 'astronomy-celestial',
                'thumbnail_url'  => '/images/templates/astronomy-celestial/thumbnail.webp',
                'description'    => 'Template pernikahan premium scientific cosmic — peta langit asli pada tanggal & jam akad, dirender dari Jakarta sebagai reference point. Navy + gold + ivory, typography Cinzel + Cormorant + EB Garamond + JetBrains Mono.',
                'default_config' => [
                    'primary_color'        => '#d4af37',
                    'primary_color_light'  => '#e8e3d3',
                    'secondary_color'      => '#1a2e4a',
                    'accent_color'         => '#7d6f9b',
                    'dark_bg'              => '#0a1929',
                    'bg_color'             => '#0a1929',
                    'text_color'           => '#e8e3d3',
                    'font_title'           => 'Cinzel',
                    'font_heading'         => 'Cormorant Garamond',
                    'font_body'            => 'EB Garamond',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'events'  => ['type' => 'color', 'value' => '#1a2e4a'],
                        'gallery' => ['type' => 'color', 'value' => '#0a1929'],
                    ],

                    'ac_groom_zodiac'             => 'libra',
                    'ac_bride_zodiac'             => 'taurus',
                    'ac_show_coords'              => true,
                    'ac_show_constellation_lines' => true,
                    'ac_star_map_style'           => 'classic',
                    'ac_parallax_depth'           => 'medium',
                    'ac_twinkle_enabled'          => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ac_groom_zodiac' => 'libra',
                    'ac_bride_zodiac' => 'taurus',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 10,
            ],

            // ── Tuscany Vineyard (Premium Destination) ────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Tuscany Vineyard',
                'slug'           => 'tuscany-vineyard',
                'thumbnail_url'  => '/images/templates/tuscany-vineyard/thumbnail.webp',
                'description'    => 'Template pernikahan premium bertema Italian destination wedding — cypress horizon golden hour, ranting zaitun, terracotta tile, dan brindisi wine-glass cheers saat RSVP.',
                'default_config' => [
                    'primary_color'          => '#c97b4a',
                    'primary_color_light'    => '#f4e4c1',
                    'secondary_color'        => '#8b9d6f',
                    'accent_color'           => '#722f2f',
                    'dark_bg'                => '#3a2a1c',
                    'font_title'             => 'Italianno',
                    'font_heading'           => 'Cormorant Garamond',
                    'font_body'              => 'Crimson Text',
                    'gallery_layout'         => 'masonry',
                    'opening_style'          => 'gate',
                    'section_backgrounds'    => [
                        'events'  => ['type' => 'color', 'value' => '#fbf4e7'],
                        'rsvp'    => ['type' => 'color', 'value' => '#f4e4c1'],
                        'closing' => ['type' => 'color', 'value' => '#3a2a1c'],
                    ],
                    'tv_italian_phrases'     => true,
                    'tv_cypress_density'     => 'medium',
                    'tv_sun_flare_intensity' => 'medium',
                    'tv_wine_cheers_sound'   => true,
                    'tv_venue_landscape'     => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'primary_color'          => '#c97b4a',
                    'secondary_color'        => '#8b9d6f',
                    'accent_color'           => '#722f2f',
                    'font_title'             => 'Italianno',
                    'font_heading'           => 'Cormorant Garamond',
                    'font_body'              => 'Crimson Text',
                    'tv_italian_phrases'     => true,
                    'tv_cypress_density'     => 'medium',
                    'tv_sun_flare_intensity' => 'medium',
                    'tv_wine_cheers_sound'   => true,
                    'tv_venue_landscape'     => true,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 13,
            ],

            // ── Japanese Ryokan (Premium Zen-Minimal) ────────────
            [
                'category_id'    => $pernikahan->id,
                'name'           => 'Japanese Ryokan',
                'slug'           => 'japanese-ryokan',
                'thumbnail_url'  => '/images/templates/japanese-ryokan/thumbnail.webp',
                'description'    => 'Zen minimal Jepang — washi paper, sumi-e brush strokes, sakura petals. Indigo + cream + sakura pink. Untuk pasangan clean-aesthetic & J-culture fans.',
                'default_config' => [
                    'primary_color'        => '#1c2e4a',
                    'primary_color_light'  => '#e8b4b8',
                    'secondary_color'      => '#e8e1d3',
                    'accent_color'         => '#8c6b3f',
                    'dark_bg'              => '#0d1a30',
                    'bg_color'             => '#f3ede4',
                    'text_color'           => '#2d2d2d',
                    'text_secondary'       => '#6b6b6b',
                    'font_title'           => 'Shippori Mincho B1',
                    'font_heading'         => 'Cormorant Garamond',
                    'font_body'            => 'Noto Sans JP',
                    'gallery_layout'       => 'grid',
                    'opening_style'        => 'fade',
                    'section_backgrounds'  => [
                        'opening'    => ['type' => 'color', 'value' => '#f3ede4'],
                        'couple'     => ['type' => 'color', 'value' => '#e8e1d3'],
                        'love_story' => ['type' => 'color', 'value' => '#f3ede4'],
                        'gallery'    => ['type' => 'color', 'value' => '#e8e1d3'],
                    ],
                    'ryokan_kanji_headers' => true,
                    'ryokan_kanji_dict'    => [
                        'opening'    => '序',
                        'couple'     => '二人',
                        'events'     => '祝典',
                        'countdown'  => '刻',
                        'love_story' => '物語',
                        'gallery'    => '写真',
                        'rsvp'       => '出席',
                        'gift'       => '贈物',
                        'wishes'     => '祝辞',
                        'closing'    => '結',
                    ],
                    'ryokan_petal_count'   => 5,
                    'ryokan_noren_kanji'   => '寿',
                    'ryokan_fuji_visible'  => true,
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'ryokan_kanji_headers' => true,
                    'ryokan_petal_count'   => 5,
                    'ryokan_noren_kanji'   => '寿',
                    'ryokan_fuji_visible'  => true,
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 12,
            ],

            // ── Vintage Postal (Premium Storybook) ───────────────
            [
                'category_id'    => $storybook->id,
                'name'           => 'Vintage Postal',
                'slug'           => 'vintage-postal',
                'thumbnail_url'  => '/images/templates/vintage-postal/thumbnail.webp',
                'description'    => 'Template pernikahan premium bergaya kartu pos vintage — kraft paper, prangko 1950an, cap pos, mesin tik, dan rute perjalanan cinta di peta antik. Cocok untuk pasangan travel-romantic / destination wedding.',
                'default_config' => [
                    'primary_color'        => '#8b3a3a',
                    'primary_color_light'  => '#a04848',
                    'secondary_color'      => '#2c4a3e',
                    'accent_color'         => '#5c4a3a',
                    'dark_bg'              => '#3a2d1f',
                    'bg_color'             => '#e8dcc4',
                    'text_color'           => '#3a2d1f',
                    'text_secondary'       => '#5c4a3a',
                    'font_title'           => 'Special Elite',
                    'font_heading'         => 'Playfair Display',
                    'font_body'            => 'Courier Prime',
                    'font_accent'          => 'Homemade Apple',
                    'gallery_layout'       => 'masonry',
                    'opening_style'        => 'gate',
                    'section_backgrounds'  => new \stdClass(),

                    'vp_couple_origin_city' => 'JAKARTA',
                    'vp_postmark_dates'     => [],
                    'vp_travel_cities'      => ['JAKARTA', 'BALI', 'KYOTO', 'PARIS', 'NEW YORK'],
                    'vp_typewriter_speed'   => 'normal',
                    'vp_paper_age'          => 'medium',
                    'vp_stamp_style'        => 'vintage-1950',
                ],
                'demo_data'      => array_merge($weddingDemo, ['custom_config' => [
                    'vp_couple_origin_city' => 'JAKARTA',
                    'vp_travel_cities'      => ['JAKARTA', 'BALI', 'TOKYO', 'PARIS', 'ROME'],
                    'vp_typewriter_speed'   => 'normal',
                    'vp_paper_age'          => 'medium',
                ]]),
                'tier'           => 'premium',
                'is_active'      => true,
                'sort_order'     => 15,
            ],
        ];

        foreach ($templates as $template) {
            Template::updateOrCreate(['slug' => $template['slug']], $template);
        }

        // Remove leftover birthday templates
        Template::whereIn('slug', ['confetti-ceria', 'biru-bintang', 'peach-balon'])->delete();
    }
}
