// resources/js/Components/invitation/templates/scene/configs/NightSkyConfig.js
export default {
    background:  '/images/templates/night-sky/scene.webp',
    fallbackBg:  'linear-gradient(180deg, #0D1B2A 0%, #1B2A4A 50%, #2E3F6F 100%)',
    modalTheme:  'night',
    fontTitle:   'Cormorant Garamond',
    hotspots: [
        {
            id:           'gallery',
            x: 22, y: 18,
            label:        'Gallery',
            section:      'gallery',
            illustration: '/images/templates/night-sky/objects/photo-frames.svg',
            animation:    'sway',
            size:         88,
        },
        {
            id:           'date_venue',
            x: 58, y: 14,
            label:        'Date & Venue',
            section:      'events',
            illustration: '/images/templates/night-sky/objects/signpost.svg',
            animation:    'sway',
            size:         72,
        },
        {
            id:           'about',
            x: 48, y: 42,
            label:        'About Us',
            section:      'couple',
            illustration: '/images/templates/night-sky/objects/couple.svg',
            animation:    'float',
            size:         92,
        },
        {
            id:           'love_story',
            x: 28, y: 58,
            label:        'Love Story',
            section:      'love_story',
            illustration: '/images/templates/night-sky/objects/lantern.svg',
            animation:    'float',
            size:         60,
        },
        {
            id:           'rsvp',
            x: 70, y: 54,
            label:        'RSVP',
            section:      'rsvp',
            illustration: '/images/templates/night-sky/objects/postbox.svg',
            animation:    'bounce',
            size:         64,
        },
        {
            id:           'gift',
            x: 62, y: 68,
            label:        'Gift',
            section:      'gift',
            illustration: '/images/templates/night-sky/objects/chest.svg',
            animation:    'pulse',
            size:         80,
        },
    ],
}
